### PR TITLE
feat: Toggle sub nav items

### LINKED ISSUE #3: Collapse shown sub nav items when clicking the most parent nav item
Hej, 

I would love to have the behavior that opened sub navigations can be collapsed when clicking the parent nav items. 

That would make it easier to explore the API.

See:
collapse

### PR DESCRIPTION
**Pull request by mischah**
… when clicking the most parent nav item.

Closes #3 :octocat: 

Hope the code matches your style 😊

### CODE REVIEW

**Comment by mischah** [comment]
Ready to be reviewed 👮

**Comment by minkyu-yi** [comment]
The style matches well. Thanks.

And I think it would be a more good feature the additional collapse buttons on the right of the anchor tags.

How about you?

**Comment by mischah** [comment]
> The style matches well. Thanks and sorry for my late review😅.

No need to be sorry 😊 

> I think it would be a more good feature the additional collapse buttons on the right of the anchor tags. 

Yeah. Would be an awesome improvement 👍 
That way people could explore the sub navigation without loading the related page.  

Going to push a commit to this PR adding a collapse button.

**Comment by mischah** [comment]
Done. Pushed a commit that introduced an icon for collapsing the sub navigation.

**Comment by mischah** [comment]
I didn't squashed my commits since the Github Merge button below allows you to squash commits 😊

**Comment by minkyu-yi** [comment]
Thanks~ 👍

**Pull request merged**
