### PR TITLE
feat: allow Examples name to be changed

### PR DESCRIPTION
**Pull request by gkatsev**
Look for `conf.templates.examplesName` to use instead of "Examples" and
default to "Examples".

### CODE REVIEW

**Comment by minkyu-yi** [comment]
Thanks for this PR 😁.
I agree with the need that users can change the tab names.
So, in my opinion, it is more useful that the option has all tab names.

How about the template option like below?

ex) - template configuration

```
"templates": {
  "tabNames": {
     "api": "API",
     "examples": "Examples"  <-- or keyname : "tutorial" ("tutorial" is jsdoc's keyname)
  }
}
```

**Comment by gkatsev** [comment]
Sounds good. I can make that change. I think `tutorial` might be better for the tab name option since that's what jsdoc calls it, as you mention. And then we just default to `Examples`.

**Comment by gkatsev** [comment]
Updated to support use the tabNames sub property. Also, updated the README.

**Comment by minkyu-yi** [comment]
Thank you :)

**Comment by gkatsev** [comment]
Rebased against develop.

**Comment by minkyu-yi** [comment]
Yeah, Thank you !~

**Pull request merged**
